# Generated by Django 5.0.3 on 2024-05-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_propertyimage_uploaded_at_alter_propertyimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
