# Generated by Django 5.0.5 on 2024-05-10 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_property_price_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default.png', upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('host', 'Vendedor'), ('guest', 'Cliente')], default='guest', max_length=10),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('review_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(limit_choices_to={'user_type': 'guest'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to='base.profile')),
                ('host', models.ForeignKey(limit_choices_to={'user_type': 'host'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='base.profile')),
            ],
        ),
    ]
